@startuml

partition recepcion_cancelacion_variacion_saldo {
    recepcion_cancelacion --> if "es recarga virtual" then
     -->[true] anular recarga virtual
     else
    -->[false] recepcion_variacion_saldo
    endif
}

partition recepcion_variacion_saldo {
    (*)  --> if variación saldo then
        -->[es incremento] "recepcion_incremento_saldo" as incremento
        else
        -->[es decremento] "recepcion_decremento_saldo" as decremento
    endif

    decremento --> if "es correcto" then
    --> [true] gestion_saldo
    else
    --> [False] moduloNotificacionesElectronicas
    endif

    incremento --> if "es correcta" then
    --> [true] existe_saldo_virtual
    if existe_saldo_virtual then
    --> [true] consolidacion_saldo_virtual
    else
    -->[false] gestion_saldo
    endif
    else
    --> [False] moduloNotificacionesElectronicas
    endif
}



partition moduloNotificacionesElectronicas #CCCCEE{

}
partition moduloGestionDeListas #CCCCEE{

}

partition recargas_automaticas {
   recargasAuto --> ===B1===
   --> moduloCobrosYAbonos


   ===B1=== --> "Gestión de saldo virtual" as virtual
   virtual -->[incrementa saldo] incremento

}

partition moduloCobrosYAbonos #CCCCEE{
    "recepción cobros y abonos" --> gestion_saldo
}

partition gestion_saldo {
    if "tipo variación" then
        --> [incremento] if "activar cuenta?" then
        --> [true] "activar cuenta e  incrementar saldo"
        else
        --> [false] incrementar saldo
        endif

    else
         --> [decremento] if "desactivar cuenta?" then
        -->[true] if "recargas automáticas" then
         -->[true] recargasAutomaticas
         else
         --> [false] "desactivar cuenta y  decrementar saldo"
         endif
         else
         --> [false] decrementar saldo
         endif


}


@enduml