kind: Service
apiVersion: v1
metadata:
  name: acl-service
spec:
  selector:
    app: acl-service
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acl-service
spec:
  selector:
    matchLabels:
      app: acl-service
  replicas: 1
  template:
    metadata:
      labels:
        app: acl-service
    spec:
      containers:
        - name: acl-service
          image: rallibaudev_acl:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env: