kind: Service
apiVersion: v1
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: acl-service
          image: rallibau-java:latest
          command: ["/bin/sh","-c"]
          args: ["java -Denv=stage -jar app.jar gateway server" ]
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env: