kind: Service
apiVersion: v1
metadata:
  name: cms-service
spec:
  selector:
    app: cms-service
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-service
spec:
  selector:
    matchLabels:
      app: cms-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cms-service
    spec:
      containers:
        - name: cms-service
          image: rallibaudev_cms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env: